name: release
on:
  push:
    branches: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: Rakshithb1/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
