name: release-chart2
on:
  push:
    branches: '*'

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    strategy:
      matrix:
        project:
          - helm
          - helm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish chart
        uses: stefanprodan/helm-gh-pages@master
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.SEC_GITHUB_TOKEN }}
          charts_dir: ${{ matrix.project }}
          charts_url: https://github.com/Rakshithb1/tstorbit2
          #owner: pojntfx
          repository: tstorbit2
          branch: gh-pages

