name: Build and Push Helm Chart

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Build Helm chart
      run: helm package charts

    - name: Clone gh-pages repository
      uses: actions/checkout@v2
      with:
        repository: tstorbit2/gh-pages
        #ref: main
        path: gh-pages

    - name: Copy Helm chart to gh-pages repository
      run: |
        mv mychart-*.tgz gh-pages/
        helm repo index gh-pages --url https://github.com/Rakshithb1/tstorbit2/gh-pages/
        cd gh-pages
        #git config user.email "github-actions@github.com"
        #git config user.name "GitHub Actions"
        git add .
        git commit -m "Add mychart-0.1.0.tgz"
        git push
