name: release-chart
on:
  push:
    branches: '*'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.SEC_GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://github.com/Rakshithb1/testorbit
          owner: Rakshithb1
          repository: testorbit
          branch: gh-pages
         # target_dir: charts
          commit_username: Rakshithb1
          #commit_email: johndoe@example.com
