name: abd-charts
on:
  push:
    branches: '*'
    paths:
      - 'helm/**'



jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.SEC_GITHUB_TOKEN }}
          charts_dir: helm/charts
          charts_url: https://github.com/Rakshithb1
          #owner: fluxcd
          repository: tstorbit2
          branch: gh-pages
          #target_dir: charts
          #commit_username: johndoe
          #commit_email: johndoe@example.com